-- Phase 8.2 (BACKEND_PLAN.md Phase 8 item 2): the NEW ServiceRequest pooling
-- loop (create -> join -> threshold -> committee-assign -> committee-relayed
-- vendor-confirm -> PricingCard freeze -> escrow), built ADDITIVELY
-- alongside the existing EVENT poll engine and Flow B (BULK_BUY_RESIDENT) —
-- neither is touched, retired, or renamed by this migration. Every new
-- column is nullable or defaulted, and every new enum value is a pure
-- addition, so every pre-8.2 row (and every existing e2e fixture) is
-- byte-for-byte unaffected. Generated by `prisma migrate diff
-- --from-config-datasource --to-schema prisma/schema.prisma --script`
-- (the migrations-directory diff needs a shadow database this project
-- doesn't configure — see prisma.config.ts) against the live dev DB, which
-- was schema-drift-free at the time (`prisma migrate status` clean at
-- 20260917150000) — reviewed by hand and found to need no edits: it is
-- already pure ADD COLUMN / CREATE TYPE / ADD VALUE / ADD FOREIGN KEY, with
-- no data movement and nothing destructive.
--
-- Safe to run as a single transaction: the two ALTER TYPE ... ADD VALUE
-- blocks (ServiceRequestStatus, ServiceRequestType) are never READ from
-- inside this same migration (no column default, CAST, or WHERE clause
-- names the new values here), which is the one restriction Postgres still
-- places on using a freshly-added enum value inside the transaction that
-- added it.

-- CreateEnum
CREATE TYPE "ServiceRequestOrigin" AS ENUM ('RESIDENT', 'COMMITTEE');

-- CreateEnum
CREATE TYPE "ParticipationStatus" AS ENUM ('ACTIVE', 'LAPSED');

-- AlterEnum
ALTER TYPE "ServiceRequestStatus" ADD VALUE 'POOLED';
ALTER TYPE "ServiceRequestStatus" ADD VALUE 'ASSIGNED';
ALTER TYPE "ServiceRequestStatus" ADD VALUE 'CONFIRMED';
ALTER TYPE "ServiceRequestStatus" ADD VALUE 'LAPSED';

-- AlterEnum
ALTER TYPE "ServiceRequestType" ADD VALUE 'SERVICE_REQUEST';

-- AlterTable: Participation additive columns (contribution, status) — see
-- Participation.contribution/status's schema doc comments.
ALTER TABLE "participations" ADD COLUMN     "contribution" DECIMAL(14,2),
ADD COLUMN     "status" "ParticipationStatus" NOT NULL DEFAULT 'ACTIVE';

-- AlterTable: ServiceRequest additive columns — see the corresponding
-- schema.prisma doc comments (origin/raisedByFlatId/threshold/
-- assignedVendorId/assignedAt/assignedByUserId/
-- vendorConfirmedContribution/frozenPricingCardId/pooledAt). All nullable;
-- no default changes any existing row's meaning.
ALTER TABLE "service_requests" ADD COLUMN     "assignedAt" TIMESTAMP(3),
ADD COLUMN     "assignedByUserId" TEXT,
ADD COLUMN     "assignedVendorId" TEXT,
ADD COLUMN     "frozenPricingCardId" TEXT,
ADD COLUMN     "origin" "ServiceRequestOrigin",
ADD COLUMN     "pooledAt" TIMESTAMP(3),
ADD COLUMN     "raisedByFlatId" TEXT,
ADD COLUMN     "threshold" INTEGER,
ADD COLUMN     "vendorConfirmedContribution" DECIMAL(14,2);

-- CreateIndex
CREATE INDEX "service_requests_assignedVendorId_idx" ON "service_requests"("assignedVendorId");

-- CreateIndex
CREATE INDEX "service_requests_raisedByFlatId_idx" ON "service_requests"("raisedByFlatId");

-- AddForeignKey
ALTER TABLE "service_requests" ADD CONSTRAINT "service_requests_raisedByFlatId_fkey" FOREIGN KEY ("raisedByFlatId") REFERENCES "flats"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_requests" ADD CONSTRAINT "service_requests_assignedVendorId_fkey" FOREIGN KEY ("assignedVendorId") REFERENCES "vendors"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_requests" ADD CONSTRAINT "service_requests_frozenPricingCardId_fkey" FOREIGN KEY ("frozenPricingCardId") REFERENCES "pricing_cards"("id") ON DELETE SET NULL ON UPDATE CASCADE;
